
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Volumen anónimo: Protege las librerías de Linux
    environment:
      - CHOKIDAR_USEPOLLING=true # Opcional: Ayuda a que el Hot Reload funcione mejor en Docker
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./backend/pyproject.toml
    volumes:
      - ./backend:/app
      - /app/.venv    
    networks:
      - net          
    depends_on:
      - db

  db:
    image: postgres:17 #TODO: Cambiar a última versión de postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net
  
networks:
  net:
    driver: bridge

volumes:
  postgres-data: